core_app/urls.py
from django.urls import path, include, reverse_lazy
from .views import singup_json, singup, ProfileViewSet, me
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as auth_token
from rest_framework import routers
from ontology_app.views import JogoViewSet


router = routers.DefaultRouter()
router.register(r'profile', ProfileViewSet, basename='profile')
router.register(r'jogo', JogoViewSet, basename='jogo')

app_name = "core_app"
urlpatterns = [
    path('login/json/', auth_token.obtain_auth_token, name='login_json'),
    path('login/', auth_views.LoginView.as_view(template_name="core_app/login.html",
                                                redirect_authenticated_user=True), name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name="core_app/logout.html"),
        name='logout'),
    path('singup/json/', singup_json, name='singup_json'),
    path('singup/', singup, name='singup'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(
             template_name="core_app/password_change_form.html",
             success_url=reverse_lazy('core_app:password_change_done')
         ), name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name="core_app/password_change_done.html"
         ), name='password_change_done'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name="core_app/password_reset_form.html",
             email_template_name="core_app/password_reset_email.html",
             success_url=reverse_lazy('core_app:password_reset_done')
         ), name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="core_app/password_reset_done.html"
         ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="core_app/password_reset_confirm.html",
             success_url=reverse_lazy('core_app:password_reset_complete')
         ), name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="core_app/password_reset_complete.html"),
         name='password_reset_complete'
         ),
    path('api/', include((router.urls, 'api'), namespace=None)),
    path('me/', me, name="me"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ontology_app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from ontology_app import views

app_name = 'ontology_app'
urlpatterns = [
    path('', views.index, name="Index"),

    path('subclasses/<str:ont_name>/<str:by_class>/',
         views.get_sub_class,
         name="Subclasses"),

    path('tree/<str:ont_name>/<str:by_class>/',
         views.get_tree_class,
         name="Tree"),

    path('instances/<str:ont_name>/<str:by_class>/',
         views.get_all_instances,
         name="Instances"),

    path('instance/<str:ont_name>/<slug:by_name>/',
         views.get_instance,
         name="Instance"),

    path('add/instance/<str:ont_name>/',
         views.create_or_update_instance,
         name="AddInstance"),

    path('delete/instance/<str:ont_name>/<str:by_class>/<str:by_instance>/',
         views.delete_instance,
         name="DeleteInstance"),

    path('ontologies/',
         login_required(views.OntologyList.as_view()), name='OntologyList'),

    path('ontology/<int:pk>/',
         login_required(views.OntologyDetail.as_view()), name='OntologyDetail'),

    path('ontology/add/',
         login_required(views.OntologyCreate.as_view()), name='OntologyCreate'),

    path('ontology/up/<int:pk>/',
         login_required(views.OntologyUpdate.as_view()), name='OntologyUpdate'),

    path('ontology/del/<int:pk>/',
         login_required(views.OntologyDelete.as_view()), name='OntologyDelete'),

]

pcomplex_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core_app.urls')),
    path('', include('ontology_app.urls'))
]

ontology_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib import admin
from django.utils import timezone, text
from django.core import validators
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage


SERVIDOR_FTP_WEB = FileSystemStorage()


class Ontology(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    file = models.FileField(
        'Arquivo',
        upload_to="ontologies/",
        storage=SERVIDOR_FTP_WEB,
        validators=[validators.FileExtensionValidator(['owl'])])

    class Meta:
        verbose_name = ("Ontology")
        verbose_name_plural = ("Ontologies")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ontology_app:OntologyDetail", kwargs={"pk": self.pk})


@receiver(pre_save, sender=Ontology)
def save_ontology(sender, instance, **kwargs):
    if not instance.slug:
        slug = "%s%s" % (instance.name, instance.created_at.microsecond)
        instance.slug = text.get_valid_filename(slug)


class OntologyAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'user', 'slug', 'created_at', 'updated_at')
    readonly_fields = ('slug', 'created_at', 'updated_at')  # 'user',
    list_display_links = ('__str__',)
    empty_value_display = '--'
    fieldsets = [
        ('Informações gerais', {'fields': ['name', 'file']}),
        ('Informações geradas automaticamente', {'classes': (
            'collapse',), 'fields': ['user', 'slug', 'created_at', 'updated_at']}),
    ]

    def save_model(self, request, obj, form, change):
        if not request.user.is_superuser:
            obj.user = request.user
        super().save_model(request, obj, form, change)


class Jogo(models.Model):
    nome = models.CharField(max_length=50)
    link = models.URLField(max_length=200, null=True, blank=True)
    icon = models.URLField(max_length=200, null=True, blank=True)
    slug = models.CharField(max_length=50)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Jogo"
        verbose_name_plural = "Jogos"

    def __str__(self):
        return self.nome


class JogoAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'slug', 'created_at', 'updated_at')
    readonly_fields = ('slug', 'created_at', 'updated_at')
    list_display_links = ('__str__',)
    empty_value_display = '--'
    search_fields = ['nome', 'slug']


@receiver(pre_save, sender=Jogo)
def save_jogo(sender, instance, **kwargs):
    if instance.link:
        slug = instance.link.split('?id=')[-1].split('&')[0]
        instance.slug = slug

ontology_app/views.py
from django.http import JsonResponse
from .ontology import Ontology as Ontology_class
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import render
from .models import Ontology, Jogo
from rest_framework.decorators import api_view
from rest_framework import serializers, viewsets
from owlready2 import sync_reasoner
sync_reasoner()


def index(request):
    tutorial = Ontology.objects.get(slug='PlayProfile')
    return render(request, "ontology_app/homepage.html",
                  {'tutorial': tutorial})


def get_all_instances(request, ont_name, by_class):
    ontology = Ontology.objects.get(slug=ont_name)
    ontology = Ontology_class(ontology.file.name)
    instances = ontology.get_instances_of(by_class)
    return JsonResponse(instances, safe=False)


def get_sub_class(request, ont_name, by_class):
    ontology = Ontology.objects.get(slug=ont_name)
    ontology = Ontology_class(ontology.file.name)
    sub_classes = ontology.get_sub_classes_of(by_class)
    return JsonResponse(sub_classes, safe=False)


def get_tree_class(request, ont_name, by_class):
    ontology = Ontology.objects.get(slug=ont_name)
    ontology = Ontology_class(ontology.file.name)
    sub_classes = ontology.get_sub_classes_of(by_class)
    tree = {}
    for branch in sub_classes:
        tree[branch] = ontology.get_sub_classes_of(branch)
    return JsonResponse(tree, safe=False)


def get_instance(request, ont_name, by_name):
    ontology = Ontology.objects.get(slug=ont_name)
    ontology = Ontology_class(ontology.file.name)
    properties = ontology.get_instance(by_name)
    return JsonResponse(properties, safe=False)


@api_view(['POST', 'PUT'])
def create_or_update_instance(request, ont_name):
    ontology = Ontology.objects.get(slug=ont_name)
    ontology = Ontology_class(ontology.file.name)
    payload = request.data
    try:
        ontology.add_instance(payload)
    except BaseException:
        pass
    properties = ontology.get_instance(payload['instance_name'])
    return JsonResponse(properties, safe=False)


@api_view(['DELETE'])
def delete_instance(request, ont_name, by_class, by_instance):
    ontology = Ontology.objects.get(slug=ont_name)
    ontology = Ontology_class(ontology.file.name)
    ontology.delete_instance(by_class, by_instance)
    ontology.get_instance(by_instance)
    return JsonResponse({})


class OntologyCreate(CreateView):
    model = Ontology
    fields = ['name', 'file']
    template_name = 'ontology_app/form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['header'] = "Publicar nova Ontologia"
        return context


class OntologyList(ListView):
    model = Ontology
    paginate_by = 10


class OntologyDetail(DetailView):
    model = Ontology


class OntologyUpdate(UpdateView):
    model = Ontology
    exclude = ('user',)
    template_name = 'ontology_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['header'] = "Editar Ontologia"
        return context


class OntologyDelete(DeleteView):
    model = Ontology
    exclude = ('user',)
    template_name = 'ontology_app/form.html'


class JogoSerializer(serializers.ModelSerializer):
    class Meta:
        model = Jogo
        fields = '__all__'
        read_only_fields = ['slug', 'nome']


class JogoViewSet(viewsets.ModelViewSet):
    serializer_class = JogoSerializer
    queryset = Jogo.objects.all()

    def list(self, request):
        ontJogos = Ontology.objects.get(slug='PlayProfile')
        ontology = Ontology_class(ontJogos.file.name)
        listaJogos = ontology.get_instances_of('Jogo')
        for jogo in listaJogos:
            Jogo.objects.get_or_create(nome=jogo)
        queryset = Jogo.objects.all()
        serializer = JogoSerializer(queryset, many=True)
        return JsonResponse(serializer.data, safe=False)

ontology_app/templates/ontology_app/footer.html
<div class="ui vertical footer segment" style="margin-top: 10em;padding:1em">
    <div class="ui section divider"></div>
    <div class="ui center aligned container">
        <div class="ui stackable inverted grid">
            <div class="five wide column">
                <h3 class="ui header">Contato</h3>
                <div class="ui list">
                    <div class="item">miltonmendes@ufersa.edu.br</div>
                    <div class="item">tieldantas@gmail.com</div>
                    <div class="item">naylsonfsa@gmail.com</div>
                </div>
            </div>

            <div class="six wide column">
                <img class="ui image centered" style="padding-top:1em"
                    src="https://overloadlab.com.br/khunters/static/khunters/logoufersa.png" alt="ufersa">
            </div>

            <div class="five wide column">
                <img class="ui small image centered"
                    src="https://overloadlab.com.br/khunters/static/khunters/overloadlab.png" alt="overloadlab">
            </div>

        </div>
        <div class="ui section divider"></div>
        <div class="ui horizontal">
            <div class="item">Copyrigth 2121 Todos os direitos reservados</div>
            <a href="/admin" class="item">admin</a>
        </div>
    </div>
</div>

ontology_app/templates/ontology_app/form.html
{% extends "ontology_app/html_base.html" %}
{% load i18n static %}
{% block content %}
<div class="ui container segment"  style="margin-top:10em">
    <div class="ui header" >{{header}}</div>
    <form class="ui form formulario " action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {% if form.errors and not form.non_field_errors %}
        <p class="ui label">
            {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </p>
        {% endif %}

        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="ui label">
            {{ error }}
        </p>
        {% endfor %}
        {% endif %}

        {% for field in form %}
        <div class="field">
            <label>{{ field.label_tag }} {{ field.errors }}</label>
            {{ field }}
        </div>
        {% endfor %}
        <button class="ui fluid button blue" type="submit">Salvar</button>
    </form>
</div>
{% endblock %}

ontology_app/templates/ontology_app/homepage.html
{% extends "ontology_app/html_base.html" %}
{% load i18n static %}
{% block content %}
    <div class="ui main container">
        <h1 class="ui header">PyComplex</h1>
        <h3 class="ui header">Acesse sua ontologia em formato JSON</h3>
        <p>PyComplex é um serviço online para lidar com ontologias. Esse serviço possibilita a publicação de ontologias na
        internet. Uma vez publicada a ontologia, será possível acessar os recursos no formato JSON</p>
        <div class="ui bulleted list">
            <div class="ui item header">
                {% if user.is_authenticated %}
                Crie uma conta
                {% else %}
                <a href="{% url 'core_app:singup' %}" >Crie uma conta</a>
                {% endif %}
            </div>
            <div class="item">
                <a href="{% url 'ontology_app:OntologyCreate' %}" class="ui header">Publique sua ontologia</a>
            </div>
            <div class="item">
                <div>
                    <div class="ui header">Acesse o conteúdo da ontologia pelo seguintes endpoints:</div>
                </div>
                <div class="list">
                    <div class="item">
                        <div class="ui header">/subclasses</div>
                        <p>O endpoint <i>/subclasses</i> retorna um array com as subclasses de uma classe específica</p>
                        <a class="ui item" href="/subclasses/{{tutorial.slug}}/Jogador/" target="blank">
                            <i class="linkify icon"></i> /subclasses/<b>{{tutorial.slug}}</b>/Jogador/
                        </a>
                        <div class="ui segment">
                            [ "Jogador", "Explorador", "Sobrevivente", "Empreendedor", "Conquistador", "Audaz",
                            "Estrategista", "Socializador" ]
                        </div>
                        <img class="ui image" src="https://overloadlab.com.br/pcomplex/static/doc/subclasses.png" />
                    </div>
                    <div class="item">
                        <div class="ui header">/tree</div>
                        <p>O endpoint <i>/tree</i> retorna um array com a árvore de uma classes</p>
                        <a class="ui item" href="/tree/{{tutorial.slug}}/Jogador/" target="blank">
                            <i class="linkify icon"></i> /tree/<b>{{tutorial.slug}}</b>/Jogador/
                        </a>
                        <div class="ui segment">
                            { Jogador: [ "Jogador", "Explorador", "Sobrevivente", "Empreendedor", "Conquistador",
                            "Audaz", "Estrategista",
                            "Socializador" ], Explorador: [ "Explorador" ], Sobrevivente: [ "Sobrevivente",
                            "Empreendedor", "Conquistador", "Audaz",
                            "Estrategista" ], Empreendedor: [ "Empreendedor", "Conquistador", "Audaz" ], Conquistador: [
                            "Conquistador", "Audaz" ],
                            Audaz: [ "Audaz" ], Estrategista: [ "Estrategista", "Conquistador", "Audaz" ], Socializador:
                            [ "Socializador" ] }
                        </div>
                        <img class="ui image" src="https://overloadlab.com.br/pcomplex/static/doc/tree.png" />
                    </div>
                    <div class="item">
                        <div class="ui header">/instances</div>
                        <p>O endpoint <i>/instances</i> retorna um array com as instâncias de uma classe específica</p>
                        <a class="ui item" href="/instances/{{tutorial.slug}}/Jogador/" target="blank">
                            <i class="linkify icon"></i> /instances/<b>{{tutorial.slug}}</b>/Jogador/
                        </a>
                        <div class="ui segment">
                            [
                            "ana",
                            "julia",
                            "marcos",
                            "mateus"
                            ]
                        </div>
                        <img class="ui image" src="https://overloadlab.com.br/pcomplex/static/doc/instances.png" />
                    </div>
                    <div class="item">
                        <div class="ui header">/instance</div>
                        <p>O endpoint <i>/instance</i> retorna um array com os <i>Types</i> e <i>Properties</i> de uma
                            instância específica</p>
                        <a class="ui item" href="/instance/{{tutorial.slug}}/julia/" target="blank">
                            <i class="linkify icon"></i> /instance/<b>{{tutorial.slug}}</b>/julia/
                        </a>
                        <div class="ui segment">
                            [ "Jogador", "Audaz", "Explorador", "Tem_habilidade Criatividade", "Tem_habilidade
                            Discernimento", "Tem_habilidade
                            Noções", "Tem_habilidade Raciocínio_lógico" ]
                        </div>
                        <img class="ui image" src="https://overloadlab.com.br/pcomplex/static/doc/instance.png" />
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
    

ontology_app/templates/ontology_app/html_base.html
<!DOCTYPE html>
<html lang="pt">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.js"></script>

    <!-- Site Properties -->
    <title>PyComplex</title>

    <style type="text/css">
        body {
            background-color: #FFFFFF;
        }

        .ui.menu .item img.logo {
            margin-right: 1.5em;
        }

        .main.container {
            margin-top: 7em;
        }

        .wireframe {
            margin-top: 2em;
        }

        .ui.footer.segment {
            margin: 5em 0em 0em;
            padding: 5em 0em;
        }
    </style>
</head>

<body>
    {% include 'ontology_app/menu.html' %}
    {% block content %}
    {% endblock %}
    {% include 'ontology_app/footer.html' %}
</body>

</html>

ontology_app/templates/ontology_app/menu.html
{% load i18n static %}
<div class="ui fixed inverted menu">
    <div class="ui container">
        <a href="/" class="header item">
            <img class="logo" src="{% static 'logo2.png' %}">
            PyComplex Tutorial
        </a>
        <a href="https://github.com/NaylsonFerreira/pcomplex" class="item">GitHub</a>
        <a class="ui item" href="{% url 'ontology_app:OntologyList' %}">Ontologias publicadas</a>
        <a class="ui item" href="{% url 'ontology_app:OntologyCreate' %}">Publicar ontologia</a>
        <div class="right menu ">
            {% if user.is_authenticated %}
            <div class="item">
                <a class="ui button basic inverted" href="{% url 'core_app:logout' %}">Sair</a>
            </div>
            {% else %}
            <div class="item">
                <a class="ui button" href="{% url 'core_app:login' %}">Entrar</a>
            </div>
            <div class="item">
                <a class="ui primary button" href="{% url 'core_app:singup' %}">Criar conta</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

ontology_app/templates/ontology_app/ontology_detail.html
{% extends "ontology_app/html_base.html" %}
{% load i18n static %}
{% block content %}
<div class="ui main container">
    <h1 class="ui header">PyComplex</h1>
    <h3 class="ui header">Ontologias publicadas</h3>
    <div class="ui items">
        <div class="item">
            <div class="middle aligned content">
                <div class="header">
                    {{ontology.name}}
                </div>
                <div class="description">
                    <div class="ui list">
                        <div class="item">
                            <i class="folder icon"></i>
                            <div class="content">
                                <div class="header">subclasses</div>
                                <div class="description">
                                    <a class="item" href="/subclasses/{{ontology.slug}}/ClassName/" target="blank">
                                        /subclasses/<b>{{ontology.slug}}</b>/ClassName/
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <i class="folder icon"></i>
                            <div class="content">
                                <div class="header">tree</div>
                                <div class="description">
                                    <a class="item" href="/tree/{{ontology.slug}}/ClassName/" target="blank">
                                        /tree/<b>{{ontology.slug}}</b>/ClassName/
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <i class="folder icon"></i>
                            <div class="content">
                                <div class="header">instances</div>
                                <div class="description">
                                    <a class="item" href="/instances/{{ontology.slug}}/ClassName/" target="blank">
                                        /instances/<b>{{ontology.slug}}</b>/ClassName/
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <i class="folder icon"></i>
                            <div class="content">
                                <div class="header">instance</div>
                                <div class="description">
                                    <a class="item" href="/instance/{{ontology.slug}}/ClassName/" target="blank">
                                        /instance/<b>{{ontology.slug}}</b>/InstanceName/
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ontology_app/templates/ontology_app/ontology_list.html
{% extends "ontology_app/html_base.html" %}
{% load i18n static %}
{% block content %}
<div class="ui main container">
    <h1 class="ui header">PyComplex</h1>
    <h3 class="ui header">Ontologias publicadas</h3>
    <div class="ui relaxed divided list">
        {% for ontology in object_list %}
        <div class="ui list">
            <div class="item">
                <i class="large jedi middle aligned icon"></i>
                <div class="content">
                    <h1 class="header">
                       <a class="ui" href="{% url 'ontology_app:OntologyDetail' ontology.pk %}">{{ontology.name}}</a>
                    </h1>
                    <div class="description">
                        {{ontology.created_at}}<br />
                        {{ontology.user.email}}
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        Você não tem nenhuma ontologia publicada
        {% endfor %}
    </div>
    {% include 'ontology_app/paginator.html' %}
</div>
{% endblock %}

ontology_app/templates/ontology_app/paginator.html
<div class="ui container  ">
    <h3 class="ui right floated header ">
        {% if page_obj.has_next %}
        <a class="ui basic black button " href="?page={{ page_obj.next_page_number }}">
            Próximo
        </a>
        <a class="ui basic black button " href="?page={{ page_obj.paginator.num_pages }}">
            Último
        </a>
        {% endif %}
    </h3>
    <h3 class="ui left floated header ">
        {% if page_obj.has_previous %}
        <a class="ui basic black button " href="?page=1">
            Primeiro
        </a>
        <a class="ui basic black button " href="?page={{ page_obj.previous_page_number }}">
            Anterior
        </a>
        {% endif %}
    </h3>
</div>

<div class="ui container  center aligned">
    <div class="current ui header ">
        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
    </div>
</div>